### ISSUE TITLE
install r8168-dkms in the Debian 10 Appsvm (sys-net-usb)

### ISSUE THREAD

**Issue by Empereur-x** [QubesOS/qubes-issues#5579]
Hi !

>I would like to use a usb wifi with my appsVm sys-net-usb but obviously there is a problem with the installation of the driver.

user@sys-net-usb:~$ sudo apt-get install r8168-dkms 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  r8168-dkms
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/97.7 kB of archives.
After this operation, 1,240 kB of additional disk space will be used.
Selecting previously unselected package r8168-dkms.
(Reading database ... 130425 files and directories currently installed.)
Preparing to unpack .../r8168-dkms_8.046.00-1_all.deb ...
Unpacking r8168-dkms (8.046.00-1) ...
Setting up r8168-dkms (8.046.00-1) ...
Loading new r8168-8.046.00 DKMS files...
dpkg: warning: version '4.19.84-1.pvops.qubes.x86_64' has bad syntax: invalid character in revision number
It is likely that 4.19.84-1.pvops.qubes.x86_64 belongs to a chroot's host
Building for 4.19.0-6-amd64, 4.19.0-6-cloud-amd64, 4.19.0-6-rt-amd64, 4.19.84-1.pvops.qubes.x86_64, firmware, initramfs, lost+found and vmlinuz
Building initial module for 4.19.0-6-amd64
Done.

r8168.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-6-amd64/updates/dkms/

depmod....

Backing up initrd.img-4.19.0-6-amd64 to /boot/initrd.img-4.19.0-6-amd64.old-dkms
Making new initrd.img-4.19.0-6-amd64
(If next boot fails, revert to initrd.img-4.19.0-6-amd64.old-dkms image)
update-initramfs........

DKMS: install completed.
Building initial module for 4.19.0-6-cloud-amd64
Done.

r8168.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-6-cloud-amd64/updates/dkms/

depmod...

Warning: Unable to find an initial ram disk that I know how to handle.
Will not try to make an initrd.

DKMS: install completed.
Building initial module for 4.19.0-6-rt-amd64
Done.

r8168.ko:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/4.19.0-6-rt-amd64/updates/dkms/

depmod...

Warning: Unable to find an initial ram disk that I know how to handle.
Will not try to make an initrd.

DKMS: install completed.
Building initial module for 4.19.84-1.pvops.qubes.x86_64
Error! Bad return status for module build on kernel: 4.19.84-1.pvops.qubes.x86_64 (x86_64)
Consult /var/lib/dkms/r8168/8.046.00/build/make.log for more information.
dpkg: error processing package r8168-dkms (--configure):
 installed r8168-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 r8168-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

>if you need make.log : 

user@sys-net-usb:~$ cat /var/lib/dkms/r8168/8.046.00/build/make.log
DKMS make.log for r8168-8.046.00 for kernel 4.19.84-1.pvops.qubes.x86_64 (x86_64)
Fri 17 Jan 2020 06:52:23 PM CET
make: Entering directory '/usr/lib/modules/4.19.84-1.pvops.qubes.x86_64/build'
  CC [M]  /var/lib/dkms/r8168/8.046.00/build/r8168_n.o
  CC [M]  /var/lib/dkms/r8168/8.046.00/build/r8168_asf.o
In file included from ./include/linux/net.h:22,
                 from ./include/linux/skbuff.h:29,
                 from ./include/linux/if_ether.h:23,
                 from ./include/uapi/linux/ethtool.h:19,
                 from ./include/linux/ethtool.h:18,
                 from ./include/linux/netdevice.h:41,
                 from /var/lib/dkms/r8168/8.046.00/build/r8168_asf.c:37:
./include/linux/random.h: In function ‘add_latent_entropy’:
./include/linux/random.h:26:39: error: ‘latent_entropy’ undeclared (first use in this function); did you mean ‘add_latent_entropy’?
  add_device_randomness((const void *)&latent_entropy,
                                       ^~~~~~~~~~~~~~
                                       add_latent_entropy
./include/linux/random.h:26:39: note: each undeclared identifier is reported only once for each function it appears in
In file included from ./include/linux/net.h:22,
                 from ./include/linux/skbuff.h:29,
                 from ./include/linux/if_ether.h:23,
                 from ./include/uapi/linux/ethtool.h:19,
                 from ./include/linux/ethtool.h:18,
                 from ./include/linux/netdevice.h:41,
                 from /var/lib/dkms/r8168/8.046.00/build/r8168_n.c:41:
./include/linux/random.h: In function ‘add_latent_entropy’:
./include/linux/random.h:26:39: error: ‘latent_entropy’ undeclared (first use in this function); did you mean ‘add_latent_entropy’?
  add_device_randomness((const void *)&latent_entropy,
                                       ^~~~~~~~~~~~~~
                                       add_latent_entropy
./include/linux/random.h:26:39: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [scripts/Makefile.build:303: /var/lib/dkms/r8168/8.046.00/build/r8168_asf.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [scripts/Makefile.build:303: /var/lib/dkms/r8168/8.046.00/build/r8168_n.o] Error 1
make: *** [Makefile:1525: _module_/var/lib/dkms/r8168/8.046.00/build] Error 2
make: Leaving directory '/usr/lib/modules/4.19.84-1.pvops.qubes.x86_64/build'

>how to fix the problem ?

**Comment by marmarek** [comment]
Installing custom modules is much easier when you switch to distribution native kernel, see here:
https://www.qubes-os.org/doc/managing-vm-kernel/#using-kernel-installed-in-the-vm

Also, you need to do that in the template, otherwise changes won't persist.

**Comment by andrewdavidwong** [comment]
Based on our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), this does not appear to be suitable for `qubes-issues`. We ask that you please send this to the `qubes-users` [mailing list](https://www.qubes-os.org/support/) instead. If, after reading our [issue reporting guidelines](https://www.qubes-os.org/doc/reporting-bugs/), you believe we are mistaken, please leave a brief comment explaining why. We'll be happy to take another look, and, if appropriate, reopen this issue. Thank you for your understanding.
