### ISSUE TITLE
Updating fedora 32 minimal template via Qubes Update fails

### ISSUE THREAD

**Issue by hexagonrecursion** [QubesOS/qubes-issues#5791]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
[qubes-template-fedora-32-minimal 4.0.1-202004291030 (r4.0)](https://github.com/QubesOS/updates-status/issues/1767)

**Brief summary**
Qubes Update fails to update a fedora 32 minimal template - a red X is shown.

**To Reproduce**
1. Install fedora 32 minimal
2. Qubes -> System Tools -> Qubes Update
3. Enable updates for qubes without known available updates
4. Click next
5. Wait until it finishes the update attempt
6. See the error message

**Expected behavior**
The update succeeds and a green V is shown

**Actual behavior**
The update fails with the following message:
```
Updating fedora-32-minimal

Error on updating fedora-32-minimal: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=fedora-32-minimal', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20
fedora-32-minimal:
      ----------
      _error:
          Failed to return clean data
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/var/tmp/.root_62a99a_salt/salt-call", line 27, in <module>
              salt_call()
            File "/var/tmp/.root_62a99a_salt/pyall/salt/scripts.py", line 440, in salt_call
              import salt.cli.call
            File "/var/tmp/.root_62a99a_salt/pyall/salt/cli/call.py", line 5, in <module>
              import salt.utils.parsers
            File "/var/tmp/.root_62a99a_salt/pyall/salt/utils/parsers.py", line 28, in <module>
              import salt.config as config
            File "/var/tmp/.root_62a99a_salt/pyall/salt/config/__init__.py", line 100, in <module>
              _DFLT_IPC_WBUFFER = _gather_buffer_space() * .5
            File "/var/tmp/.root_62a99a_salt/pyall/salt/config/__init__.py", line 89, in _gather_buffer_space
              import salt.grains.core
            File "/var/tmp/.root_62a99a_salt/pyall/salt/grains/core.py", line 40, in <module>
              from platform import _supported_dists
          ImportError: cannot import name '_supported_dists' from 'platform' (/usr/lib64/python3.8/platform.py)
      stdout:
```

**Screenshots**
none

**Additional context**
Apparently salt does not yet support python 3.8
https://github.com/saltstack/salt/issues/55310

**Solutions you've tried**
Workaround: templates can be updated manually by running `sudo dnf upgrade` in each template

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
none

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
none

**Comment by fepitre** [comment]
I've fixed it for dom0: https://github.com/QubesOS/qubes-salt/pull/1. I don't know yet which strategy to adopt for VM too.

**Comment by marmarek** [comment]
I'd give a little more time upstream to fix this (and also annoying warnings about deprecated imports). I would really like to avoid going into business of packaging "generic" stuff for various linux distributions just because upstream distribution provides incompatible versions (like here: Fedora 32 shipping python 3.8 and salt package not compatible with python 3.8).

**Comment by Rudd-O** [comment]
I doubt upstream will fix this in time for F32 release.  But @fepitre 's patch can be upstreamed as a patch to Fedora Salt now.

**Comment by fepitre** [comment]
In the mean time: https://src.fedoraproject.org/rpms/salt/pull-request/1

**Comment by marmarek** [comment]
Also opened a bug here: https://bugzilla.redhat.com/show_bug.cgi?id=1830518

**Comment by marmarek** [comment]
linking to #5761

**Comment by 92VV3M42d3v8** [comment]
Following error occurs when updating fedora-32 template on Qubes-4.1 April build.
Updating Fedora-32

Fedora-32:
- Rendering SLS 'base:update.qubes-vm' failed: Jinja variable 'dict object' has no attribute 'os'

**Comment by marmarek** [comment]
> Rendering SLS 'base:update.qubes-vm' failed: Jinja variable 'dict object' has no attribute 'os'

It is this: https://github.com/saltstack/salt/issues/57509 (another issue with salt in Fedora 32...)

**Comment by fepitre** [comment]
Fedora has commited the 3001rc1 which includes the major work on python3.8: https://src.fedoraproject.org/rpms/salt/c/9c5f252840c18bfcfc4aad8a302f1389f8d73c5d?branch=f32

**Comment by fepitre** [comment]
Salt is now in Fedora repository with python 3.8 support and it update is working through salt.
