### ISSUE TITLE
i18n causing regressions

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#2637]
Qubes-manager notifications have been broken since https://github.com/QubesOS/qubes-manager/commit/4946d7b8d0dfc945b6da0f37e2219df51ade9dac because .tr() is attempted to be called on self in places where self is not the QApplication (or anything deriving from QObject?). ([[1]](https://github.com/QubesOS/qubes-manager/blob/4946d7b8d0dfc945b6da0f37e2219df51ade9dac/qubesmanager/main.py#L99), [[2]](https://github.com/QubesOS/qubes-manager/blob/4946d7b8d0dfc945b6da0f37e2219df51ade9dac/qubesmanager/main.py#L105), [[3]](https://github.com/QubesOS/qubes-manager/blob/4946d7b8d0dfc945b6da0f37e2219df51ade9dac/qubesmanager/main.py#L120), almost certainly others)

This results in stack traces like the following:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 1505, in run
    self.loop()
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 1491, in loop
    self.process_events()
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 1287, in process_events
    self._default_proc_fun(revent)
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 924, in __call__
    return _ProcessEvent.__call__(self, event)
  File "/usr/lib/python2.7/site-packages/pyinotify.py", line 644, in __call__
    return meth(event)
  File "/usr/lib64/python2.7/site-packages/qubesmanager/main.py", line 105, in process_IN_CLOSE_WRITE
    trayIcon.showMessage(unicode(self.tr(
AttributeError: 'QubesManagerFileWatcher' object has no attribute 'tr'
```

I [tried just `s/self.tr(/app.tr(/` everywhere](https://github.com/jpouellet/qubes-manager/commit/df0c6235ab9359129377aa9f2bf5a486d185586c), but app isn't available everywhere either, so apparently we need to review the scopes on a call-by-call basis? I feel like there should be a cleaner way to address this, but I don't know what that would be.

**Comment by jpouellet** [comment]
There are also more regressions where .tr() is callable, but still missing conversion from QString to something with .format(). https://github.com/QubesOS/qubes-manager/commit/d073b3582db7d9d14431106e323ae42a9178c53a did not hit all cases, for example [here](https://github.com/QubesOS/qubes-manager/blob/ed8f889c9276e3d136c8fde900a01605a746bb93/qubesmanager/main.py#L1455-L1456).

Definitely don't release to qubes-dom0-current yet ;)

**Comment by marmarek** [comment]
> ([1], [2], [3], almost certainly others)

Any other example? Most of the code _is_ in QObject based classes - the only exceptions I remember are:
 - few classes at the beginning of `main.py` (you've hit this one)
 - `block.py`, `clipboard.py` - excluded from translation for this reason
 - `backup_utils.py`, `appmenu_select.py` - nothing to translate

As for wrapping `self.tr` with `unicode` - this is rather ugly, but mostly because QString is incompatible with python builtin `str`/`unicode`... The alternative is to switch to QString completely and use `QString.arg` (`%1`, `%2`, etc) instead of `str.format` (`{}` or named variant). IMHO consistency with our other python modules is more important than consistency with PyQt.

**Comment by jpouellet** [comment]
It seems I was wrong. All .tr()s except those three (and [this](https://github.com/QubesOS/qubes-manager/blob/master/qubesmanager/backup_utils.py#L94)) indeed do seem to operate on self in a class deriving from QSomething.

PR to correct just those 3: https://github.com/QubesOS/qubes-manager/pull/26
