### ISSUE TITLE
Qubes 4.3: assignments() method is missing from DeviceCollection objects

### ISSUE THREAD

**Issue by tasket** [QubesOS/qubes-issues#10097]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.3 testing

### Brief summary
assignments() getter method is missing from returned DeviceCollection objects (qubesadmin).

### Steps to reproduce
```
import qubesadmin
d = qubesadmin.Qubes().app.domains
a = d["sys-net"].devices["pci"].assignments()
```

### Expected behavior
'a' is _generator object DeviceCollection.assignments_ object.

### Actual behavior
AttributeError: 'DeviceCollection' object has no attribute 'assignments'.

### Additional information
The error occurs when running `wyng-util-qubes` to restore vms from a Wyng archive. The util is trying to erase existing device assignments before making assignments stored in the backup.  This works correctly on Qubes 4.2.
@kennethrrosen

**Comment by Minimalist73** [comment]
I encountered this issue while restoring my wyng backup on my new 4.3 system. I had to comment out the entire device assignment part to proceed.

Since the device API changed in Qubes 4.3, a [special script](https://github.com/QubesOS/qubes-dist-upgrade/blob/main/scripts/qubes-dist-upgrade-r4.3-pci.py) was created in `qubes-dist-upgrade` to unassign and assign devices to support the new changes. You are probably looking for `get_assigned_devices()` instead?

**Comment by tasket** [comment]
@Minimalist73 Thanks!  I'd still rather use the old API method (instead of supporting old + new), but this could serve as a workaround.

**Comment by tasket** [comment]
Seems there will be more differences than assignments() vs get_assigned_devices().  It would be nice if Qubes could 'thunk' between the old and new API calls.

**Comment by tasket** [comment]
There are also differences in the rest of _qubesadmin.devices_ module.  However, they are not all documented.

The 4.3 docs mention the use of _DeviceAssignment()_ objects, but that class is only detailed in the 4.2 docs.  My attempt to create assignments with the old _DeviceAssignment()_ syntax doesn't work; for example it raises an error "DeviceAssignment.\_\_init\_\_() got an unexpected keyword argument 'backend_domain'".

**Comment by marmarek** [comment]
The Devices API changed in 4.3, it's one of the major new features. Parts are similar, but unfortunately it's not fully compatible, so code using this API will need some changes.

Generally API doc can be found at https://dev.qubes-os.org/projects/core-admin/en/latest/qubes-devices.html (and classes linked from there).
There is also a high-level overview of changes at https://github.com/QubesOS/qubes-core-admin/pull/614#issuecomment-2415287445

**Comment by tasket** [comment]
Thanks for the overview, Marek.

@Minimalist73 wyng-util-qubes has been updated in the [09beta](https://codeberg.org/tasket/wyng-util-qubes/src/branch/09beta) branch to utilize the new 4.3 API – it makes different calls depending on the Qubes version.
